import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import Navbar from "@/components/sections/navbar";
import { Footer } from "@/components/sections/footer";
import FloatingQuoteButton from "@/components/ui/floating-quote-button";

export const metadata: Metadata = {
    title: "Evergreen Group Of Companies",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const orchidsEnabled = process.env.NEXT_PUBLIC_ENABLE_ORCHIDS === "true";
    const orchidsTargetOrigin = process.env.NEXT_PUBLIC_ORCHIDS_TARGET_ORIGIN;

    return (
        <html lang="en">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin="anonymous"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body className="antialiased">
                <Navbar />
                {children}
                <Footer />
                <FloatingQuoteButton />

                {orchidsEnabled && orchidsTargetOrigin && (
                    <>
                        <VisualEditsMessenger />
                        <Script
                            id="orchids-browser-logs"
                            src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts/orchids-browser-logs.js"
                            strategy="afterInteractive"
                            data-orchids-project-id="5f5702b0-00ea-450f-84bb-61992efa636a"
                        />
                        <ErrorReporter />
                        <Script
                            src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
                            strategy="afterInteractive"
                            data-target-origin={orchidsTargetOrigin}
                            data-message-type="ROUTE_CHANGE"
                            data-include-search-params="true"
                            data-only-in-iframe="true"
                            data-debug="false"
                            data-custom-data='{"appName":"Evergreen","version":"1.0.0"}'
                        />
                    </>
                )}
            </body>
        </html>
    );
}
